### PR TITLE
[FEAT] Added restart button to the default results page

### LINKED ISSUE #313: [FEAT] Add a restart button to the default Results Page
#### Describe the bug:
Currently, there is a restart button on the Results Page when there are no Results. It would be good to also have a button for the normal Results Page when there are results.

### Additional context:
You can copy+paste the 'Back' button from other pages (without the <Link>) and then replace the onClick handler to `() => window.location.reload()` and the text to `Restart`

### PR DESCRIPTION
**Pull request by MKTPR**
* added restart button to successful game result page

Restart - button (blue) has been added

image

Closes #313

### CODE REVIEW

**Review by UltimaKuma — APPROVED** [review]
Nice and short implementation that works well.

**Comment by reeved** [comment]
Hey Maric, while we wait to determine whats causing the font size issues, could you please revert your changes to the quotes :) they should be single quotes instead of double to be consistent with the rest of the project

**Comment by MKTPR** [comment]
> Hey Maric, while we wait to determine whats causing the font size issues, could you please revert your changes to the quotes :) they should be single quotes instead of double to be consistent with the rest of the project

thats been reverted! thanks for the review

**Review by reeved — APPROVED** [review]
LGTM. Thanks Maric!

**Comment by skyn310198** [comment]
LGTM, thanks for a nice feature

**Review by skyn310198 — APPROVED** [review]

**Pull request merged**
