### PR TITLE
[WIKI] .env example file

### LINKED ISSUE #260: [WIKI] Add .env.example file to show which environment variables are required for the project to run
Currently there is no example for the variables that are required in the backend's `.env` file, other than a brief description in the README. A common convention is for projects to have a `.env.example` file which can be copied, modified and renamed for use as the `.env` file.

This change would make it quicker for people to set up their environment, and make the project setup easier to understand for people who are unfamiliar with the concept of environment variable files.

### PR DESCRIPTION
**Pull request by seif-y**
--
name: .env example file
about: Adding an example for the `.env` file to improve ease of setup for project
title: "[WIKI] .env example file"
labels: documentation, Backend
assignees: @seif-y 

---

Adds a file called `.env.example` that can be copied and used as the `.env` file.

Closes #260

### CODE REVIEW

**Comment by SiyuQian** [comment]
LGTM. Good comments. Well explained how to use the file as an example.

**Review by SiyuQian — APPROVED** [review]

**Review by MKTPR — APPROVED** [review]
Looks good. I guess we're gonna have to make new PRs for the new main with the same changes tho?

**Comment by seif-y** [comment]
> Looks good. I guess we're gonna have to make new PRs for the new main with the same changes tho?

I've changed the base branch to `main2` for this one. If it's all good with you I can merge this one into `main2` instead of making a new PR

**Comment by MKTPR** [comment]
> > Looks good. I guess we're gonna have to make new PRs for the new main with the same changes tho?
> 
> I've changed the base branch to `main2` for this one. If it's all good with you I can merge this one into `main2` instead of making a new PR

Yeap sounds good👍👍

**Review by jge385 — APPROVED** [review]
LGTM!

**Pull request merged**
