### PR TITLE
[FEAT] Add autocomplete location search box

### PR DESCRIPTION
**Pull request by bche536**
Added a google api autocomplete search box component to show nearby locations in preferences

### CODE REVIEW

**Review by aniket-rai — CHANGES_REQUESTED** [review]
From discord discussion:
- separated function is missing
- API key is public so not safe to commit
- workflow is a bit confused -- nearby search needs to be added before prod ready
- will discuss more at some point today

**Review by aniket-rai — APPROVED** [review]
Changes requested prior will be incorporated in the next PR. Current files and changes are approved.

**Review by PJhaveri02 — APPROVED** [review]
Current changes to files are approved,

**Review by OverCry — APPROVED** [review]
LGTM. When this PR is accepted, it seems like I can combine it with my PR on the preference page

**Pull request merged**
