### PR TITLE
[FIX] Fixed all snapshot test errors

### LINKED ISSUE #332: [BUG] Snapshot tests unchanged after certain implementations
***

#### Describe the bug:
After making changes to the front end, the snapshots for those specific pages which is used for testing remained unchanged, which resulted in unit tests to fail. 

### To Reproduce the bug:
A clear description of the steps to reproduce the behaviour:
1. cd frontend (from the root directory)
2. npm install
3. npm run test
4. select "a" as the option to run all tests

This should provide you with the failing tests

### PR DESCRIPTION
**Pull request by MKTPR**
Fixes #332 

Bug was due to snapshots which weren't changed after certain implementations to the frontend.

### CODE REVIEW

**Review by parfei — APPROVED** [review]
Tests all pass now, great work :D

**Review by SiyuQian — CHANGES_REQUESTED** [review]
All other stuff looks good to me but I suggest that we put the SVG into a separate file (.svg file) then import it instead of rendering it so we keep the JS file clean?

**Comment by reeved** [comment]
> All other stuff looks good to me but I suggest that we put the SVG into a separate file (.svg file) then import it instead of rendering it so we keep the JS file clean?

The SVG is already in its own file (/Common/MapsPinpoint.js) - it's just been wrapped in a function to be a React Component I guess? not sure since there aren't any benefits I believe compared to storing it in a .svg file. But yea, refactoring the SVG to not be a Component could be considered in the future :)

**Comment by SiyuQian** [comment]
> > All other stuff looks good to me but I suggest that we put the SVG into a separate file (.svg file) then import it instead of rendering it so we keep the JS file clean?
> 
> The SVG is already in its own file (/Common/MapsPinpoint.js) - it's just been wrapped in a function to be a React Component I guess? not sure since there aren't any benefits I believe compared to storing it in a .svg file. But yea, refactoring the SVG to not be a Component could be considered in the future :)

To be honest, I don't 100% agree with "there aren't any benefits I believe compared to storing it in a .svg file" but at this stage, I think it is a "nice to have" request. 
Because storing an SVG file in a .svg file (which is best practice) could make it being cached correctly (eg. the Nginx/Apache is set up for the project). Anyway, I changed the 'requested changes' to 'approval'. @reeved

**Review by SiyuQian — APPROVED** [review]
LGTM

**Comment by reeved** [comment]
> To be honest, I don't 100% agree with "there aren't any benefits I believe compared to storing it in a .svg file" but at this stage, I think it is a "nice to have" request.
> Because storing an SVG file in a .svg file (which is best practice) could make it being cached correctly (eg. the Nginx/Apache is set up for the project). Anyway, I changed the 'requested changes' to 'approval'. @reeved

oh didnt know! but yea i agree storing it in a .svg file is best practise.

**Review by jge385 — APPROVED** [review]
LGTM   passed all tests now. Good job!~

**Pull request merged**
