### PR TITLE
Removed CreateGroup folder

### PR DESCRIPTION
**Pull request by OverCry**
Because of a previous design decision, the folder became redundent. Currently, the folder of this content has been removed.

### CODE REVIEW

**Comment by OverCry** [comment]
I feel like this change is going to cause plenty of cascading merge conflicts.

**Review by Alxjlv — APPROVED** [review]
A simple fix with a lot of files touched. Looks solid to me

**Review by jemimahmartinez — APPROVED** [review]
Surely if any, the merge conflicts won't be too bad to work with. Otherwise, it LGTM 👌

**Review by DavidHuangz — APPROVED** [review]
Good Job. Thanks for renaming the imports to make it more clear and efficient and formating the code into a more precise and appealing presentation. Should be functional without the unnecessarily creategroup folder so that all our files are relevant in the project.

**Pull request merged**
