### PR TITLE
[FEAT] Adding join page capabilities

### PR DESCRIPTION
**Pull request by OverCry**
Currently incomplete.

Need to wait for an end point for checking if the code provided is legit.

### CODE REVIEW

**Comment by OverCry** [comment]
Currently waiting for an endpoint to check if the code provided is correct

**Comment by OverCry** [comment]
Also need to check with socket team for the name passing

**Comment by OverCry** [comment]
Now waiting for endpoints to be accepted to add code check

**Comment by OverCry** [comment]
Pushing this PR so websockets can be used to check for correct name code

**Review by Tianrens — APPROVED** [review]

**Review by David-Xia0 — APPROVED** [review]

**Pull request merged**
