### PR TITLE
[TEST] Swiping page testing

### PR DESCRIPTION
**Pull request by ayushjani**
Adding tests for the frontend components used on the swiping page.

### CODE REVIEW

**Comment by OverCry** [comment]
Is there a reason why your have the swipe cards test done in the same folder as your swiping folder? I would have thought the common components would have its own test suite in the Common folder

**Comment by ayushjani** [comment]
@OverCry Oh yes my bad, that is definitely a good point, will make that change for the next commit 👍

**Comment by OverCry** [comment]
Is there anything you're still missing in this PR?

**Review by OverCry — DISMISSED** [review]
Looks Good~! You also moved the common components into the Common test folder.

**Comment by ayushjani** [comment]
> Looks Good~! You also moved the common components into the Common test folder.

**Review by OverCry — APPROVED** [review]
Looks Good~!

**Review by DavidHuangz — APPROVED** [review]
Good work, congratulations on getting your test passed. Good work!

**Pull request merged**
