### PR TITLE
[FEAT] Add Google API key endpoint (served via process vars) to backend

### PR DESCRIPTION
**Pull request by aniket-rai**
Added backend endpoint to serve google API keys from process variables.

### CODE REVIEW

**Review by David-Xia0 — DISMISSED** [review]
I think what @Tianrens meant was have layered API, so the GOOGLE_API_KEY should never reach the frontend code. 

Instead, create endpoints in the backend that mimic the google API, and in the backend retrieve the information for the google API wihtt eh API Key

**Comment by Tianrens** [comment]
> I think what @Tianrens meant was have layered API, so the GOOGLE_API_KEY should never reach the frontend code.
> 
> Instead, create endpoints in the backend that mimic the google API, and in the backend retrieve the information for the google API wihtt eh API Key

Was just about to type this...

**Comment by aniket-rai** [comment]
> > I think what @Tianrens meant was have layered API, so the GOOGLE_API_KEY should never reach the frontend code.
> > Instead, create endpoints in the backend that mimic the google API, and in the backend retrieve the information for the google API wihtt eh API Key
> 
> Was just about to type this...

Ah so refactor the places where we are calling the different API's to the backend and only get the response. Righty-o. That's gonna be a lot bigger than expected lol. Thanks guys

**Comment by aniket-rai** [comment]
Decision made to restrict API with domain and IP rather than backend techniques atm due to time crunch.

**Review by David-Xia0 — APPROVED** [review]

**Review by PJhaveri02 — APPROVED** [review]

**Pull request merged**
