### PR TITLE
[FEAT] Add result data visual

### PR DESCRIPTION
**Pull request by jemimahmartinez**
Added a Pie chart data visualisation that shows the distribution of votes across the given restaurants in the 'Results' page 

Still need to add tests

Addresses issue #130

### CODE REVIEW

**Review by ayushjani — DISMISSED** [review]
Looks good to me!

**Comment by jemimahmartinez** [comment]
Sorry, its not up for review just yet!!

**Review by ayushjani — APPROVED** [review]
Looking good!

**Review by David-Xia0 — APPROVED** [review]

**Comment by Alxjlv** [comment]
Code looks good to me - I'll pull down and test locally shortly

**Pull request merged**
