### PR TITLE
Add unit tests for get session/id to backend 

### LINKED ISSUE #244: [Test] Add unit tests for Get sessions/id endpoint
Add unit tests for Get sessions/id endpoint.

### PR DESCRIPTION
**Pull request by cecilia-yin**
Closes #244

### CODE REVIEW

**Review by lilichenyuxin — COMMENTED** [review]
you forgot to link the issue~~

**Review by Jaysce — APPROVED** [review]
LGTM

**Review by lilichenyuxin — COMMENTED** [review]
you forgot to link the issue~~

**Review by lilichenyuxin — APPROVED** [review]
LGTM

**Pull request merged**
