### PR TITLE
[TEST] Test for Common components

### PR DESCRIPTION
**Pull request by OverCry**
Snapshots for common components which have yet to be done.

Currently done UserInput

### CODE REVIEW

**Comment by OverCry** [comment]
Added for Map Pinpoint

**Comment by OverCry** [comment]
Added for Help component.

**Comment by OverCry** [comment]
Location Helper uses global variables so its very ICKY

**Review by ayushjani — APPROVED** [review]
Well done! Really good job :)

**Review by jemimahmartinez — APPROVED** [review]
Great, thorough test cases!

**Pull request merged**
