### PR TITLE
[TEST] Add StartPage and JoinPage snapshot

### PR DESCRIPTION
**Pull request by OverCry**
Added snapshot testing for the start page

As the start page does not contain any complex components, nor require any inputs, the test is very simple

### CODE REVIEW

**Comment by OverCry** [comment]
Changed PR name as both pages have little code.

**Review by Alxjlv — COMMENTED** [review]
Looks pretty solid - just a quick question, should we be comitting the generated snapshots?

**Review by jemimahmartinez — COMMENTED** [review]
Ez pz 👌nice work. Alex makes a good point with the `snap` files, perhaps we should add them to the `.gitignore` file?

**Comment by OverCry** [comment]
I'm pretty certain I remember being told that we are supposed to keep the snapshots. I'll try to find a source online just in case my memory is wrong

**Comment by OverCry** [comment]
https://jestjs.io/docs/snapshot-testing

image

**Review by David-Xia0 — APPROVED** [review]
Nice Job Wong

**Review by jemimahmartinez — APPROVED** [review]
Awesome 👌 noice job

**Pull request merged**
