### PR TITLE
[TEST] Results page testing

### LINKED ISSUE #74: [FEAT] Add Results page
Adding Results page to present the top restaurant choice 

Map Modal: #91, #92 
Data Visualisation: #181, #130

### PR DESCRIPTION
**Pull request by jemimahmartinez**
Added snapshot testing for components used on the Results page

Closes #74

### CODE REVIEW

**Comment by OverCry** [comment]
Similar to my comment on ayush's PR, is there a reason why your have MapModal done in the same folder? I would have thought the common components would have its own test suite in the Common folder

**Comment by jemimahmartinez** [comment]
@OverCry oh yeah I just kept all my tests together just cause the MapModal is used in the `ResultsPage`. I can definitely create a `__tests__` folder in the `Common` folder and move the MapModal test there

**Comment by jemimahmartinez** [comment]
Currently, when running the tests locally all the tests run and pass. However, the CI is failing when running and testing the `ResultPage` test, saying that the snapshot doesn't match. 

The reason why it might not be matching could be because the img src isn't being retrieved properly - this works on the SwipingPage though

**Review by David-Xia0 — APPROVED** [review]
LGTM, it finally works yay

**Review by DavidHuangz — APPROVED** [review]
Awesome work on getting those snapshots and tests done. The tests are very well done! Congratulations!

**Pull request merged**
