### PR TITLE
[BUG] Fixes issue when no restaurants returned.

### LINKED ISSUE #314: [BUG] No error message when Restaurants can't be found
#### Describe the bug:
At the moment, if the app can't find any restaurants that match your preference, you won't find out. Instead, you will just keep clicking the "Go" button with no response at all. 

### To Reproduce the bug:
A clear description of the steps to reproduce the behaviour:

1. Create a lobby
2. Enter 'Lake Taupo, Waikato, New Zealand' as the location
3. Leave every other parameter as default
4. Click the "Go" button
5. Observe absolutely nothing

Ideally, there would be an error message of some sort that would let you know to update your preferences in order to widen the search parameters.

### What it should look like:
image

### Additional context:
In `Common/LocationHelper.js`, the `getNearbyRestaurants` method returns a promise that is expected to be information about the restaurant cards. When there are no restaurants found, this is does not get resolved. This is because `status !== OK`. Instead, `status === ZERO_RESULTS`. In `3.Preferences/Preferences.js`, you can add a condition in the `handleSearch` method that checks if `data === 'ZERO_RESULTS'` and if so, add a warning message somewhere. This message should be hidden again once search parameters get changed.

A way of going about this would be to create another `useState` for `showErrorMessage` which when true, shows the message, and when false, hides it. This would get set to false everytime a parameter gets changed.

Make sure to use the CSS Property `visibility: visible | hidden` for the error message to prevent UI elements from shifting.

### PR DESCRIPTION
**Pull request by Dhors**
* Added error message when no restaurants returned.
* Error message removed when search parameters changed.
* Restyled preferences screen to hold error message.

Screenshots of new preferences screen when error message displayed
image

mobile view
image

Closes #314

### CODE REVIEW

**Review by reeved — CHANGES_REQUESTED** [review]
looks great! any reason why the package-lock files were included in this PR? there doesn't seem to be any changes made to packages

**Review by reeved — CHANGES_REQUESTED** [review]
Hey Daniel,

After further testing, I've noticed that you did not reset the message on the Price Picker's `onChange`. Could you please add it there too. Thanks!

**Comment by Dhors** [comment]
> Hey Daniel,
> 
> After further testing, I've noticed that you did not reset the message on the Price Picker's `onChange`. Could you please add it there too. Thanks!

Oh my bad, I missed that one completely. I added it now.
Thanks for letting me know Reeve.

**Comment by Dhors** [comment]
> looks great! any reason why the package-lock files were included in this PR? there doesn't seem to be any changes made to packages

I removed the files from the PR, no idea why they were put in.

**Review by reeved — APPROVED** [review]
LGTM. Thanks for the changes Daniel :D

**Review by atha670 — APPROVED** [review]
Looks good, should be ready to merge now

**Pull request merged**
