### PR TITLE
[FEAT] Adding create page capabilities

### PR DESCRIPTION
**Pull request by OverCry**
Currently Incomplete.

Need to decide how prices are 'create'. Either hardcode or take from an API.
Need to implement location 
Need to implement cuisines
Need to use endpoint to posting the session
Need to generate session code

### CODE REVIEW

**Comment by OverCry** [comment]
Still need to add location on.
Also need CSS but if this can be done by someone else.

**Comment by Alxjlv** [comment]
Currently out of date - conflicts must be resolved

**Comment by OverCry** [comment]
Change back to draft to resolve some expected merge conflicts

**Comment by OverCry** [comment]
Just needs styling to be added

**Comment by bche536** [comment]
How are you currently moving the location around?

What does sendCoordinates do?

**Review by bche536 — APPROVED** [review]
LGTM! i have looked over the changes in person

**Pull request merged**
