### PR TITLE
[TEST] Lobby and CountDown testing

### PR DESCRIPTION
**Pull request by DavidHuangz**
Added snapshot testing for Lobby and CountDown.

Mocking the sockets is required for testing to work. Spent so long on this  :(

### CODE REVIEW

**Review by jemimahmartinez — APPROVED** [review]
No issues from me, well done! Ooop as I wrote this, the CI build failed lol 

Should be an easy import fix - might have been from the newest merged in code changes when the CreateGroup folder was deleted

**Comment by DavidHuangz** [comment]
> No issues from me, well done! Ooop as I wrote this, the CI build failed lol
> 
> Should be an easy import fix - might have been from the newest merged in code changes when the CreateGroup folder was deleted

Yep, it was due to the CreateGroup commit. Fixed now though.

**Review by jemimahmartinez — APPROVED** [review]
Speedy fix David 👌 LGTM

**Review by OverCry — APPROVED** [review]
Looks Good~!

**Pull request merged**
