### PR TITLE
[BUG] Result screen fails when no restaurant is 'liked' 

### LINKED ISSUE #240: [BUG] Result screen fails when no restaurant is 'liked'
### To Reproduce the bug:

1. Go to 'yumble.xyz'
2. Click on 'Create Room'
3. Enter a random location
4. Click 'go'
5. Click 'go'
6. Do not click any location

As no restaurant has been selected, some indicator to show no preference has been shown.

On yumble.xyz,  a whitescreen is given.
On localhost, 
image

* OS: Windows
* Browser: Chrome

### PR DESCRIPTION
**Pull request by jge385**
--
name: Result screen fails when no restaurant is 'liked' 
about: The result screen should not fail when no restaurant is 'liked', it should show the no result message.
title: "[Bug] Fixes "
labels: Frontend, bug
assignees: @jge385 

---

* BUG

Fixes: display no result message when no restaurant is 'liked'
image

Closes #240.

### CODE REVIEW

**Review by MKTPR — APPROVED** [review]
I've cloned the branch and tested that it runs locally. The try again button takes you back to the starting screen as well. Looks great!

**Review by seif-y — APPROVED** [review]
Looks good, and works as expected :)

**Review by SiyuQian — CHANGES_REQUESTED** [review]
The code is working well! Except the commits need a bit clean up as you mentioned in the WeChat. I reckon we could create a new branch and create a new pull request based on that to avoid the issue. 

Also, I noticed the comment for the variable ```hasResult``` says 'it is used for testing'. Is it true? Or you forgot to change it after the actual implementation. lol. BTW, you committed a ```package-lock.json``` file.

**Review by MKTPR — APPROVED** [review]

**Comment by SiyuQian** [comment]
Closing this PR as we should merge to branch ```main2```. See PR#266.

**Pull request closed without merging**
